
import createError from "http-errors"



/**create signup user
 * 
 * @param {*email,password} data 
 */

const signUpUser = async (data:any) => {
  try {
   
  } catch (error) {
    throw error
  }
}





/**check user already there
 * 
 * @param {email id} email 
 */
const checkUser = async (email:any) => {
  try {
 
  } catch (error) {
    throw error
  }
}

/**check user already there
 * 
 * @param {email id} email 
 */
 const loginUser = async (email:any) => {
  try {
  
  } catch (error) {
    throw error
  }
}



export  {
  signUpUser,
  checkUser,
  loginUser
}